version: "3"

# for local testing

services:
  nginx-proxy:
    container_name: pager-nginx-proxy
    image: nginx:alpine
    ports: 
      - "9999:80"
    networks:
      - internal
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./data/:/var/www/html/

  nginx-internal:
    container_name: pager-nginx-internal
    image: nginx:1.17.6-alpine
    networks:
      - internal
    volumes:
      - ./config/internal.conf:/etc/nginx/conf.d/default.conf
      - ./data/:/var/www/html/

  php:
    container_name: pager-php
    image: php:fpm-alpine
    read_only: true
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./flag:/flag

networks:
  internal:
    driver: bridge
